# **welcome to Numpy** 

In [1]:
import numpy as np

In [2]:
myarr = np.array([2,4,5,6], np.int8)

In [3]:
print("hello world")

hello world


In [4]:
myarr.dtype

dtype('int8')

In [5]:
# array creation. conversion from other python structures

In [6]:
listarray = np.array([[1,3,4],[3,5,2],[2,6,6]])

In [7]:
listarray

array([[1, 3, 4],
       [3, 5, 2],
       [2, 6, 6]])

In [8]:
listarray.dtype

dtype('int32')

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [12]:
zeros = np.zeros((2, 4))

In [13]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
zeros.shape

(2, 4)

In [15]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
lspace = np.linspace(1,50,3)

In [17]:
lspace

array([ 1. , 25.5, 50. ])

In [18]:
emp = np.empty((4,4))

In [19]:
emp

array([[4.67296746e-307, 1.69121096e-306, 7.56590980e-307,
        8.01092456e-307],
       [6.23059726e-307, 2.22522597e-306, 1.33511969e-306,
        1.37962320e-306],
       [9.34604358e-307, 9.79101082e-307, 1.78020576e-306,
        1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        1.60221208e-306]])

In [20]:
emplike = np.empty_like(lspace)

In [21]:
emplike

array([ 1. , 25.5, 50. ])

In [22]:
ide = np.identity(34)

In [23]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
ide.shape

(34, 34)

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr= arr.ravel()

In [30]:
arr.shape

(99,)

In [31]:
 x = [[1,2,3],[4,5,6],[7,8,9]]

In [32]:
ar = np.array(x)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar.sum(axis= 0)

array([12, 15, 18])

In [35]:
ar.sum(axis= 1)

array([ 6, 15, 24])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
ar.flat

In [38]:
for item in ar.flat : print(item)

1
2
3
4
5
6
7
8
9


In [39]:
ar.ndim

2

In [40]:
ar.size

9

In [41]:
ar.shape

(3, 3)

In [42]:
ar.nbytes

36

In [43]:
one = np.array([1,3,44,43,2])

In [44]:
one.argmax()

2

In [45]:
one.argmin()

0

In [46]:
one.argsort()

array([0, 4, 1, 3, 2], dtype=int64)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [49]:
ar.argmin()

0

In [50]:
ar.argmax()

8

In [51]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [52]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [53]:
ar.argsort(axis= 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [54]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar2 = ([[3, 2, 3],
       [4, 3, 6],
       [1, 3, 9]])

In [58]:
ar + ar2

array([[ 4,  4,  6],
       [ 8,  8, 12],
       [ 8, 11, 18]])

In [59]:
ar * ar2

array([[ 3,  4,  9],
       [16, 15, 36],
       [ 7, 24, 81]])

In [60]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [61]:
arr.sum()

4851

In [62]:
ar.sum()

45

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
type(np.where(ar>5))

tuple

In [65]:
np.count_nonzero(ar)

9

In [66]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [ ]:
import numpy as np

In [68]:
np.empty_like

<function numpy.empty_like>

In [69]:
np.ones_like

<function numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)>

In [70]:
np.empty

<function numpy.empty>

In [71]:
print("Hello world")

Hello world


In [72]:
var * var2

NameError: name 'var' is not defined

In [73]:
varr * varr2

NameError: name 'varr' is not defined

In [77]:
ar = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
ar + arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [82]:
ar / arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
ar.size

9

In [84]:
ar.shape

(3, 3)